name: TODO

task_name: TODO

shape_meta: &shape_meta
  # acceptable types: rgb, low_dim
  obs:
    # image:
    #     shape: *image_shape
    #     type: rgb
    point_cloud:
      shape: [1024, 6]
      type: point_cloud
    agent_pos:
      shape: [16]
      type: low_dim
  action:
    shape: [16]

dataset:
  _target_: diffusion_policy_3d.dataset.real_franka_dataset.RealFrankaDataset
  zarr_path: TODO
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1'}
  pad_after: ${eval:'${n_action_steps}-1'}
  seed: 42
  val_ratio: 0.02
  max_train_episodes: 90
